name: Deploy to Main Server

on:
  push:
    branches:
      - main  # main 브랜치에 push 실행

env:
  directory: /root/docker/

jobs:
  deploy-main:
    if: github.ref == 'refs/heads/main'  # main 브랜치일 때만 실행
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
          PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          PORT: ${{ secrets.SERVER_PORT }}
        run: |
          sshpass -p "${PASSWORD}" ssh -p ${PORT} -o StrictHostKeyChecking=no ${USER}@${HOST} << 'EOF'
            cd /root/ERP_System/
            git pull
            cd /root/ERP_System/view/
            apt install npm
            npm install
            nohup npm run build 2>&1 &
            cd /root/ERP_System/gateway/
            mvn clean package
            mv -f /root/ERP_System/gateway/target/gateway-0.0.1-SNAPSHOT.jar /root/docker/gateway.jar
            chmod 755 ${directory}gateway.jar
            cd /root/ERP_System/mfr/
            mvn clean package
            mv -f /root/ERP_System/mfr/target/mfr-0.0.1-SNAPSHOT.jar /root/docker/mfr.jar
            chmod 755 ${directory}mfr.jar
            cd /root/ERP_System/oauth/
            mvn clean package
            mv -f /root/ERP_System/oauth/target/oauth-0.0.1-SNAPSHOT.jar /root/docker/oauth.jar
            chmod 755 ${directory}oauth.jar
            cd /root/ERP_System/stg/
            mvn clean package
            mv -f /root/ERP_System/stg/target/stg-0.0.1-SNAPSHOT.jar /root/docker/stg.jar
            chmod 755 ${directory}stg.jar
            cd /root/ERP_System/trs/
            mvn clean package
            mv -f /root/ERP_System/trs/target/trs-0.0.1-SNAPSHOT.jar /root/docker/trs.jar
            chmod 755 ${directory}trs.jar
          EOF
