name: Deploy to Main Server

on:
  push:
    branches:
      - main  # main 브랜치에 push 실행

jobs:
  deploy-main:
    if: github.ref == 'refs/heads/main'  # main 브랜치일 때만 실행
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
          PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          PORT: ${{ secrets.SERVER_PORT }}
        run: |
          sshpass -p "${PASSWORD}" ssh -p ${PORT} -o StrictHostKeyChecking=no ${USER}@${HOST} << 'EOF'
            cd /root/ERP_System/
            git pull
            cd /root/ERP_System/view/
            apt install npm
            npm install
            nohup npm run build 2>&1 &
            nohup npm run preview 2>&1 &
            EOF
